import React from 'react';
import {AbsoluteFill, Composition, Sequence, interpolate, spring, useCurrentFrame, registerRoot} from 'remotion';
import examples from '../web/examples.json';

const C={paper:'#FAF7F2',ink:'#1F1D1A',moss:'#5A7A4E',muted:'#6B6560',line:'#DCD8CE',soft:'#ECEFDF',rose:'#F1E3DA'};
const serif='Georgia, serif';
const ease=(f,a=0,b=20)=>interpolate(f,[a,b],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
function Stones({size=60,animated=false}){const f=useCurrentFrame();return <svg width={size} height={size*34/24} viewBox="0 0 24 34">{[[12,28,10.5,3.6,.95,0],[11.5,19.5,7.8,3.2,.78,-6],[12.5,11,5.2,3.6,.62,9]].map(([cx,cy,rx,ry,o,r],i)=><g key={i} opacity={animated?ease(f,i*7,i*7+15):1} transform={`translate(0,${animated?(1-spring({frame:f-i*7,fps:30,config:{damping:15}}))*-15:0})`}><ellipse cx={cx} cy={cy} rx={rx} ry={ry} fill={["#2B2B2B","#555555","#7B7B7B"][i]} transform={`rotate(${r} ${cx} ${cy})`}/></g>)}</svg>}
const Label=({children})=><div style={{fontSize:16,letterSpacing:2,textTransform:'uppercase',color:C.moss,fontWeight:600}}>{children}</div>;
function Brand(){return <div style={{display:'flex',gap:18,alignItems:'center'}}><Stones size={26}/><span style={{fontFamily:serif,fontSize:35}}>Cairn</span><span style={{color:C.muted,fontSize:24}}>×</span><span style={{fontSize:26,letterSpacing:-1}}>Jev <span style={{color:C.muted,fontWeight:300}}>Lab</span></span></div>}
function Reveal({at=0,children,style={}}){const f=useCurrentFrame();const p=spring({frame:f-at,fps:30,config:{damping:20}});return <div style={{opacity:ease(f,at,at+14),transform:`translateY(${(1-p)*28}px)`,...style}}>{children}</div>}
function Shell({children}){const f=useCurrentFrame();return <AbsoluteFill style={{background:C.paper,color:C.ink,fontFamily:'Arial, sans-serif',padding:'38px 64px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',borderBottom:`1px solid ${C.line}`,paddingBottom:18}}><Brand/><span style={{fontSize:15,color:C.muted}}>AN OPEN EXPERIMENT IN AI MEMORY</span></div>{children}<div style={{position:'absolute',bottom:28,left:64,right:64,display:'flex',justifyContent:'space-between',color:C.muted,fontSize:15}}><span>Animated explanation · recorded Jev outputs · no live inference</span><span>lab.cairn.ink</span></div><div style={{position:'absolute',bottom:0,left:0,height:4,width:`${f/659*100}%`,background:C.moss}}/></AbsoluteFill>}
function Intro(){const f=useCurrentFrame();return <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',height:510}}><div><Reveal><Label>Before it becomes a memory</Label></Reveal><Reveal at={8}><h1 style={{fontFamily:serif,fontSize:80,lineHeight:1.08,fontWeight:400,letterSpacing:-3,margin:'22px 0'}}>What should<br/>your AI remember?</h1></Reveal><Reveal at={24}><p style={{fontSize:25,color:C.muted}}>Evidence first. Then a decision.</p></Reveal></div><div style={{width:270,height:270,border:`1px solid ${C.line}`,borderRadius:'50%',display:'flex',alignItems:'center',justifyContent:'center',transform:`rotate(${Math.sin(f/40)*3}deg)`}}><Stones size={120} animated/></div></div>}
function Proposal(){const f=useCurrentFrame();const x=examples.find(x=>x.id==='h13');return <div style={{paddingTop:32}}><Reveal><Label>01 / A proposal is not a decision</Label></Reveal><div style={{display:'flex',gap:30,marginTop:25}}><Reveal at={8} style={{width:565}}><div style={{background:'#FFFDFA',border:`1px solid ${C.line}`,borderRadius:20,padding:30,height:340}}><Label>Source passage</Label><p style={{fontFamily:serif,fontSize:30,lineHeight:1.4}}>{x.source}</p><div style={{height:4,width:interpolate(f,[30,65],[0,350],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}),background:C.moss}}></div></div></Reveal><div style={{flex:1}}><Reveal at={26}><div style={{padding:30,border:`1px solid ${C.line}`,borderRadius:20}}><Label>Proposed memory</Label><p style={{fontSize:29,lineHeight:1.35,marginBottom:0}}>{x.candidate}</p></div></Reveal><Reveal at={64}><div style={{marginTop:18,background:C.rose,borderRadius:20,padding:'18px 30px',display:'flex',alignItems:'center',gap:25}}><span style={{fontFamily:serif,fontSize:57}}>Skip</span><span style={{fontSize:19,lineHeight:1.4}}>The source does not<br/>support adoption.</span></div></Reveal></div></div><Reveal at={80}><p style={{fontSize:16,color:C.muted}}>Recorded case h13 · both policies reject the candidate · jev-1.13.0</p></Reveal></div>}
function Threshold(){const f=useCurrentFrame();const x=examples.find(x=>x.id==='h01');return <div style={{paddingTop:30}}><Reveal><Label>02 / Same response. Different thresholds.</Label></Reveal><Reveal at={5}><h2 style={{fontFamily:serif,fontSize:44,fontWeight:400,margin:'18px 0'}}>A lasting preference worth keeping?</h2></Reveal><div style={{display:'flex',gap:28}}><Reveal at={12} style={{width:550}}><div style={{padding:25,border:`1px solid ${C.line}`,borderRadius:18,background:'#FFFDFA'}}><Label>Source</Label><p style={{fontSize:22,lineHeight:1.45}}>{x.source}</p><Label>Candidate</Label><p style={{fontSize:22,lineHeight:1.4,marginBottom:0}}>{x.candidate}</p></div></Reveal><div style={{flex:1}}>{[['Support',.79],['Useful later',.69],['Faithful',.76]].map(([label,value],i)=><Reveal key={label} at={20+i*8}><div style={{display:'flex',justifyContent:'space-between',fontSize:17,marginBottom:8}}><span>{label}</span><span>{Math.round(value*100)}% confidence</span></div><div style={{height:7,background:C.line,borderRadius:4,marginBottom:18}}><div style={{height:7,width:`${value*100*ease(f,25+i*8,55+i*8)}%`,background:C.moss,borderRadius:4}}/></div></Reveal>)}<div style={{display:'flex',gap:14}}>{[['Baseline · 0.75','Defer',C.rose],['Preview · 0.40','Save',C.soft]].map(([label,value,bg],i)=><Reveal key={value} at={65+i*15} style={{flex:1}}><div style={{padding:22,background:bg,borderRadius:15}}><div style={{fontSize:16,color:C.muted}}>{label}</div><div style={{fontFamily:serif,fontSize:49,marginTop:8}}>{value}</div></div></Reveal>)}</div></div></div><Reveal at={90}><p style={{fontSize:16,color:C.muted}}>Recorded case h01 · provider confidence is not accuracy · preview remains experimental</p></Reveal></div>}
function Outro(){const f=useCurrentFrame();return <div style={{paddingTop:35}}><Reveal><Label>Explore the evidence</Label></Reveal><Reveal at={5}><h2 style={{fontFamily:serif,fontSize:62,fontWeight:400,margin:'20px 0 28px'}}>An open lab. A testable standard.</h2></Reveal><div style={{display:'flex',gap:20}}>{[['100','synthetic English cases'],['3','typed judgments'],['264 ms','mean API time in this run']].map(([n,l],i)=><Reveal key={n} at={12+i*8} style={{flex:1}}><div style={{borderTop:`1px solid ${C.line}`,paddingTop:20}}><div style={{fontFamily:serif,fontSize:63}}>{n}</div><div style={{fontSize:20,color:C.muted,marginTop:8}}>{l}</div></div></Reveal>)}</div><Reveal at={30}><p style={{fontSize:16,color:C.muted,marginTop:24}}>AI-authored labels · latency includes network time · not a speed guarantee</p></Reveal><Reveal at={40}><div style={{display:'flex',alignItems:'center',gap:25,marginTop:27}}><div style={{background:C.moss,color:C.paper,padding:'18px 30px',borderRadius:40,fontSize:27}}>Try the lab ↗</div><div><div style={{fontSize:28}}>lab.cairn.ink</div><div style={{fontSize:16,color:C.muted,marginTop:6}}>Replay without a key · run new cases locally</div></div></div></Reveal></div>}
function Lab(){return <Shell><Sequence layout="none" durationInFrames={105}><Intro/></Sequence><Sequence layout="none" from={105} durationInFrames={195}><Proposal/></Sequence><Sequence layout="none" from={300} durationInFrames={210}><Threshold/></Sequence><Sequence layout="none" from={510} durationInFrames={150}><Outro/></Sequence></Shell>}
function Cover(){return <AbsoluteFill style={{background:C.paper,color:C.ink,padding:64,fontFamily:'Arial, sans-serif'}}><Brand/><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginTop:52}}><div><Label>An open experiment in AI memory</Label><h1 style={{fontFamily:serif,fontSize:78,fontWeight:400,lineHeight:1.02,letterSpacing:-3,margin:'24px 0'}}>Before it becomes<br/>a memory.</h1><p style={{fontSize:24,color:C.muted}}>Supported. Useful. Faithful.</p></div><div style={{border:`1px solid ${C.line}`,borderRadius:'50%',width:260,height:260,display:'flex',alignItems:'center',justifyContent:'center'}}><Stones size={120}/></div></div><div style={{position:'absolute',bottom:45,left:64,right:64,borderTop:`1px solid ${C.line}`,paddingTop:22,display:'flex',justifyContent:'space-between',fontSize:18,color:C.muted}}><span>Built by Cairn · powered by Jev · independent project</span><span>lab.cairn.ink ↗</span></div></AbsoluteFill>}
function Icon(){return <AbsoluteFill style={{background:C.paper,alignItems:'center',justifyContent:'center'}}><div style={{width:414,height:414,border:`2px solid ${C.line}`,borderRadius:108,display:'flex',alignItems:'center',justifyContent:'center',position:'relative'}}><Stones size={190}/><div style={{position:'absolute',right:35,bottom:30,background:C.moss,color:C.paper,fontFamily:'Arial',fontSize:24,letterSpacing:3,padding:'10px 14px',borderRadius:12}}>LAB</div></div></AbsoluteFill>}
registerRoot(()=> <><Composition id="Lab" component={Lab} width={1280} height={720} fps={30} durationInFrames={660}/><Composition id="Cover" component={Cover} width={1280} height={640} fps={30} durationInFrames={1}/><Composition id="Icon" component={Icon} width={512} height={512} fps={30} durationInFrames={1}/></>);
